### ISSUE TITLE
damask module not found!

### ISSUE THREAD

**Issue by muh-hassani** [conda-forge/damask-feedstock#69]
I tried a fresh environment and installed damask, but I can not import damask module at all.
The error is:
```
>>> import damask
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'damask'
```

Additionally old versions of damask is not available any more! I think this is really a bad practice for reproducibility of the old workflows!

**Comment by MarDiehl** [comment]
`conda install damask=3.0.0a4=py39hb4560e5_15` should work.
There are now `MPICH` and `openMPI` variants.
Dependencies are totally screwed up, `HDF5` works on `osx` only for versions > 1.10, but `vtk` requires 1.10.
For some reasons, `conda install damask` installs `py39ha770c72_8`.
Probably I need to mark a bunch of package revisions as broken.

> I tried a fresh environment and installed damask, but I can not import damask module at all.
> The error is:
> 
> ```
> >>> import damask
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
> ModuleNotFoundError: No module named 'damask'
> ```
> 
> Additionally old versions of damask is not available any more! I think this is really a bad practice for reproducibility of the old workflows!
All old versions are there, they are just marked as broken because they are promoted as 3.0.0 even though they are alpha versions.

**Comment by MarDiehl** [comment]
> Additionally old versions of damask is not available any more! I think this is really a bad practice for reproducibility of the old workflows!

There is no way to delete packages (maybe for legal reasons) so all packages are still there. However, they are released as DAMASK 3.0.0 even though they are an alpha version. When I asked the Conda-Forge admins to change the version string, they suggested to rather mark them as broken. That's what I did.

**Comment by muh-hassani** [comment]
@MarDiehl thanks for your response. Currently the previous versions (3.0.0 with various builts) can not be found!

**Comment by MarDiehl** [comment]
@muh-hassani: You need to specify exactly the version you want to have, the old versions do not show up anymore.
They are visible on conda-forge.
But there is also now a new working version, it is currently hidden due to some hick-ups. It should become the default soon.

**Comment by muh-hassani** [comment]
@MarDiehl I specified the build and version. The old version which used to work for me, was `damask=3.0.0=*_9`. I look forward to the newer updates. I will try and update here.  Thank you.

**Comment by MarDiehl** [comment]
@muh-hassani: `conda install -c conda-forge/label/broken damask=3.0.0=py39h1c92b0e_9` finds a package on my linux (I get a conflict, but I assume that it should work for you)

**Comment by muh-hassani** [comment]
@MarDiehl thanks, it worked 👍

**Comment by MarDiehl** [comment]
now the new package should work as well.
It is split to enable installation of the python code on windows.
MacOS is only partly supported (either Fortran or Python, i.e. no metapackge) due to conflicting dependencies.
